import { toast } from 'react-toastify';
export const addedToCart = () => toast('Successfully Added to cart ');
export const removedFromCart = () => toast('Removed from cart');
export const addedToWishlist = () => toast('Successfully Added to wishlist ');
export const removedFromWishlist = () => toast('Removed from wishlist');
export const loggedIn = () => toast('Successfully Logged In');
export const loggedOut = () => toast('Logged Out');
export const addedAddress = () => toast('Successfully Added Address');
export const removedAddress = () => toast('Address Removed');
export const selectAddress = () => toast('Please select an Address');
export const noAddress = () => toast('No Address Found');
export const signedUp = () => toast('Signed up successfully');
export const orderPlaced = () => toast('Order Placed successfully');
