import { v4 as uuid } from 'uuid';

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Men's Slim-Fit Shirt",
    description: 'A classic slim-fit shirt for men in a range of colors',
    price: '49.99',
    category: 'men',
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0752/6435/products/NAPLES-MENSSOLIDSHIRT-YELLOWhero2_765x.jpg?v=1659454364',
    rating: 4.5,
    numReviews: 10,
    colors: ['white', 'blue', 'black', 'red'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    _id: uuid(),
    title: "Women's Skinny Jeans",
    description: 'Trendy and versatile skinny jeans for women',
    price: '59.99',
    category: 'women',
    imageUrl: 'https://example.com/womens-skinny-jeans.jpg',
    rating: 4.8,
    numReviews: 25,
    colors: ['blue', 'black', 'grey'],
    sizes: ['24', '26', '28', '30'],
  },
  {
    _id: uuid(),
    title: 'Unisex Hoodie',
    description: 'A cozy and stylish hoodie for both men and women',
    price: '79.99',
    category: 'unisex',
    imageUrl: 'https://example.com/unisex-hoodie.jpg',
    rating: 4.2,
    numReviews: 5,
    colors: ['black', 'grey', 'navy'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    _id: uuid(),
    title: "Men's Swim Shorts",
    description: 'Stylish and comfortable shorts for swimming',
    price: '39.99',
    category: 'men',
    imageUrl: 'https://example.com/mens-swim-shorts.jpg',
    rating: 4.2,
    numReviews: 8,
    colors: ['blue', 'black', 'red'],
    sizes: ['30', '32', '34', '36'],
  },

  {
    _id: uuid(),
    title: "Women's Skirt",
    description: 'A flowy and feminine skirt for women',
    price: '79.99',
    category: 'women',
    imageUrl: 'https://example.com/womens-skirt.jpg',
    rating: 4.6,
    numReviews: 22,
    colors: ['blue', 'black', 'pink'],
    sizes: ['S', 'M', 'L'],
  },

  {
    _id: uuid(),
    title: "Men's Leather Jacket",
    description: 'A classic leather jacket for men',
    price: '199.99',
    category: 'men',
    imageUrl: 'https://example.com/mens-leather-jacket.jpg',
    rating: 4.8,
    numReviews: 25,
    colors: ['black', 'brown'],
    sizes: ['S', 'M', 'L', 'XL'],
  },

  {
    _id: uuid(),
    title: "Women's Denim Jacket",
    description: 'A trendy and versatile jacket for women',
    price: '119.99',
    category: 'women',
    imageUrl: 'https://example.com/womens-denim-jacket.jpg',
    rating: 4.7,
    numReviews: 18,
    colors: ['blue', 'black'],
    sizes: ['S', 'M', 'L'],
  },
  {
    _id: uuid(),
    title: "Men's T-Shirt",
    description: 'A comfortable and casual T-shirt for men',
    price: '29.99',
    category: 'men',
    imageUrl: 'https://example.com/mens-tshirt.jpg',
    rating: 4.4,
    numReviews: 6,
    colors: ['white', 'black', 'grey', 'navy'],
    sizes: ['S', 'M', 'L', 'XL'],
  },

  {
    _id: uuid(),
    title: "Men's Dress Shoes",
    description: 'Classic and stylish dress shoes for men',
    price: '129.99',
    category: 'men',
    imageUrl: 'https://example.com/mens-dress-shoes.jpg',
    rating: 4.5,
    numReviews: 12,
    colors: ['black', 'brown'],
    sizes: ['8', '9', '10', '11'],
  },
  {
    _id: uuid(),
    title: "Women's Sneakers",
    description: 'Comfortable and stylish sneakers for women',
    price: '99.99',
    category: 'women',
    imageUrl: 'https://example.com/womens-sneakers.jpg',
    rating: 4.3,
    numReviews: 15,
    colors: ['white', 'black', 'pink'],
    sizes: ['6', '7', '8', '9'],
  },
];
